### ISSUE TITLE
Non US keyboard layouts problematic

### ISSUE THREAD

**Issue by marcdownie** [OpenEndedGroup/Field2#45]
Key test case: alt-0 inserts a character with a Swedish keyboard layout

**Comment by marcdownie** [comment]
Potentially fixed in 55024d74d69746856ef0b6595c5dbb5eb8282ea8.

**Comment by jharaldson** [comment]
Alt+0 now works with Swedish keyboard, however there are a few keyboard combinations that still don't work. A few examples below. Also the keyboard is extended to include the three Swedish letters 'å', 'ä', 'ö'. 

Shift+comma(to the right of M) = ';' but gives a colon ':'.
Alt+2 = '@', but gives nothing
Shift+7 = '/' but gives '?'

**Comment by jharaldson** [comment]
Any progress on this?
